#!/local/perl/bin/perl

=head1 NAME

stripchart - stripchart control program

=head1 SYNOPSIS

 % stripchart -help
 % stripchart -cfg scuba.ini

=head1 DESCRIPTION

Program to display stripcharts using the specified configuration file.

=head1 OPTIONS

The following options are supported:

=over 4

=item B<-cfg>

Name of the configuration file to use to configure the stripchart.
By default the stripchart will use "chart.ini".

=item B<-help>

Print help information.

=item B<-version>

Print stripchart version.

=item B<-man>

Print the documentation to STDOUT.

=back

=cut

use warnings;
use strict;
use Getopt::Long;
use Pod::Usage;

use JAC::StripChart;

use vars qw/ $DEBUG /;
$DEBUG = 0;

# Options
my ($help, $man, $version, $cfgfile);
my $status = GetOptions("help" => \$help,
                        "man" => \$man,
                        "version" => \$version,
                        "cfg=s" => \$cfgfile,
                       );

pod2usage(1) if $help;
pod2usage(-exitstatus => 0, -verbose => 2) if $man;

if ($version) {
  my $id = '$Id$ ';
  print "Stripchart tool for ORAC-DR pipeline\n";
  print " CVS revision: $id\n";
  exit;
}

# determine the configuration file whereabouts
$cfgfile = 'chart.ini' unless $cfgfile;

# Now create the stripchart
my $st = new JAC::StripChart( $cfgfile );

$st->init;
$st->MainLoop;

exit;

=head1 AUTHOR

Tim Jenness E<lt>t.jenness@jach.hawaii.eduE<gt>

=head1 COPYRIGHT

Copyright (C) 2005 Particle Physics and Astronomy Research Council.
All Rights Reserved.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful,but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place,Suite 330, Boston, MA  02111-1307, USA

=head1 SEE ALSO

L<xstripchart>, L<JAC::StripChart>

=cut
